Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
AllCops:
  NewCops: enable
